### ISSUE TITLE
How to make horizontal recylerview section wise 

### ISSUE THREAD

**Issue by Feroz-Istar** [truizlop/SectionedRecyclerView#21]
How to make horizontal recylerview section wise  like vertical and Grids. I am not able to create different section horizontally.

**Comment by truizlop** [comment]
It should work exactly the same as in vertical. Make sure the views have the appropriate sizes. If you don't provide more details, I cannot help you.

**Comment by Feroz-Istar** [comment]
We want to have a layout like this http://3.bp.blogspot.com/-w6K1uiMAg28/Vnvu40--xGI/AAAAAAAAINc/X2gp4zcx_Xk/s1600/Screenshot_2015-12-24-17-51-46.png if we try to put recylerview layout manager horizontal its not creating the section all the data is coming inline.

**Comment by truizlop** [comment]
That is the expected behavior of a RecyclerView; the issue is not on this library. To create a layout as the one you want to create, you need to have a `RecyclerView` with vertical layout and sectioning, and you need to set a layout for each row that includes a nested `RecyclerView` for the horizontal scroll, or a `ViewPager`.
